//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogEntities
    {
        public long Id { get; set; }
        public string EntityName { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> AuditLogId { get; set; }
        public string CustomData { get; set; }
        public int Action { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual AuditLogs AuditLogs { get; set; }
    }
}
