//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditLogs()
        {
            this.AuditLogEntities = new HashSet<AuditLogEntities>();
        }
    
        public long Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ServiceName { get; set; }
        public string MethodName { get; set; }
        public string Parameters { get; set; }
        public System.DateTime ExecutionTime { get; set; }
        public int ExecutionDuration { get; set; }
        public string ClientIpAddress { get; set; }
        public string ClientName { get; set; }
        public string BrowserInfo { get; set; }
        public string Exception { get; set; }
        public Nullable<long> ImpersonatorUserId { get; set; }
        public Nullable<int> ImpersonatorTenantId { get; set; }
        public string CustomData { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> Component { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLogEntities> AuditLogEntities { get; set; }
        public virtual Users Users { get; set; }
    }
}
