//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityChanges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityChanges()
        {
            this.EntityPropertyChanges = new HashSet<EntityPropertyChanges>();
        }
    
        public long Id { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public byte ChangeType { get; set; }
        public long EntityChangeSetId { get; set; }
        public string EntityId { get; set; }
        public string EntityTypeFullName { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual EntityChangeSets EntityChangeSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityPropertyChanges> EntityPropertyChanges { get; set; }
    }
}
