//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLogs
    {
        public long Id { get; set; }
        public long OrganizationUnitId { get; set; }
        public int TenantId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid CorrelationId { get; set; }
        public int Level { get; set; }
        public int Source { get; set; }
        public Nullable<long> RobotId { get; set; }
        public string ProcessName { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public Nullable<long> QueueDefinitionId { get; set; }
        public string Message { get; set; }
        public bool Acknowledged { get; set; }
        public Nullable<System.DateTime> AcknowledgeTime { get; set; }
        public Nullable<long> AcknowledgeUserId { get; set; }
        public string AcknowledgeUserName { get; set; }
    }
}
