//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobEvents
    {
        public long Id { get; set; }
        public int TenantId { get; set; }
        public long OrganizationUnitId { get; set; }
        public Nullable<long> ReleaseId { get; set; }
        public Nullable<long> RobotId { get; set; }
        public string HostMachineName { get; set; }
        public long JobId { get; set; }
        public int Action { get; set; }
        public int State { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    
        public virtual Jobs Jobs { get; set; }
        public virtual Users Users { get; set; }
    }
}
