//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.Sessions = new HashSet<Sessions>();
        }
    
        public long Id { get; set; }
        public int TenantId { get; set; }
        public System.Guid Key { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int State { get; set; }
        public Nullable<long> RobotId { get; set; }
        public Nullable<long> ReleaseId { get; set; }
        public int Source { get; set; }
        public System.Guid BatchExecutionKey { get; set; }
        public string Info { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public long OrganizationUnitId { get; set; }
        public Nullable<long> StartingScheduleId { get; set; }
        public int Type { get; set; }
        public string InputArguments { get; set; }
        public string OutputArguments { get; set; }
        public string HostMachineName { get; set; }
    
        public virtual ProcessSchedules ProcessSchedules { get; set; }
        public virtual Releases Releases { get; set; }
        public virtual Robots Robots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
