//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTriggers
    {
        public long Id { get; set; }
        public int TenantId { get; set; }
        public long OrganizationUnitId { get; set; }
        public long JobId { get; set; }
        public int Status { get; set; }
        public int TriggerType { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<System.DateTime> ResumeTime { get; set; }
        public string TriggerMessage { get; set; }
    
        public virtual Jobs Jobs { get; set; }
    }
}
