//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public long Id { get; set; }
        public long OrganizationUnitId { get; set; }
        public int TenantId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Level { get; set; }
        public string WindowsIdentity { get; set; }
        public string ProcessName { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public string RobotName { get; set; }
        public string Message { get; set; }
        public string RawMessage { get; set; }
        public Nullable<long> MachineId { get; set; }
    }
}
