//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessSchedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessSchedules()
        {
            this.Jobs = new HashSet<Jobs>();
            this.Robots = new HashSet<Robots>();
        }
    
        public long Id { get; set; }
        public bool Enabled { get; set; }
        public int TenantId { get; set; }
        public long ReleaseId { get; set; }
        public string StartProcessCron { get; set; }
        public int StartStrategy { get; set; }
        public string StartProcessCronDetails { get; set; }
        public string StopProcessExpression { get; set; }
        public string ExternalJobKey { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public long OrganizationUnitId { get; set; }
        public Nullable<int> StopStrategy { get; set; }
        public string Name { get; set; }
        public string TimeZoneId { get; set; }
        public bool UseCalendar { get; set; }
        public Nullable<System.DateTime> StopProcessDate { get; set; }
        public string InputArguments { get; set; }
        public Nullable<long> QueueDefinitionId { get; set; }
        public long ItemsActivationThreshold { get; set; }
        public long ItemsPerJobActivationTarget { get; set; }
        public int MaxJobsForActivation { get; set; }
        public Nullable<long> CalendarId { get; set; }
    
        public virtual Calendars Calendars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs> Jobs { get; set; }
        public virtual QueueDefinitions QueueDefinitions { get; set; }
        public virtual Releases Releases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Robots> Robots { get; set; }
    }
}
