//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_FIRED_TRIGGERS
    {
        public string SCHED_NAME { get; set; }
        public string ENTRY_ID { get; set; }
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public string INSTANCE_NAME { get; set; }
        public long FIRED_TIME { get; set; }
        public long SCHED_TIME { get; set; }
        public int PRIORITY { get; set; }
        public string STATE { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public Nullable<bool> IS_NONCONCURRENT { get; set; }
        public Nullable<bool> REQUESTS_RECOVERY { get; set; }
    }
}
