//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_JOB_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRTZ_JOB_DETAILS()
        {
            this.QRTZ_TRIGGERS = new HashSet<QRTZ_TRIGGERS>();
        }
    
        public string SCHED_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public string DESCRIPTION { get; set; }
        public string JOB_CLASS_NAME { get; set; }
        public bool IS_DURABLE { get; set; }
        public bool IS_NONCONCURRENT { get; set; }
        public bool IS_UPDATE_DATA { get; set; }
        public bool REQUESTS_RECOVERY { get; set; }
        public byte[] JOB_DATA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRTZ_TRIGGERS> QRTZ_TRIGGERS { get; set; }
    }
}
