//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_PAUSED_TRIGGER_GRPS
    {
        public string SCHED_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
    }
}
