//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueDefinitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueueDefinitions()
        {
            this.ProcessSchedules = new HashSet<ProcessSchedules>();
            this.QueueItems = new HashSet<QueueItems>();
            this.QueueProcessingRecords = new HashSet<QueueProcessingRecords>();
            this.QueueProcessingRecordsOld = new HashSet<QueueProcessingRecordsOld>();
            this.QueueProcessingRecordsStaging = new HashSet<QueueProcessingRecordsStaging>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MaxNumberOfRetries { get; set; }
        public bool AcceptAutomaticallyRetry { get; set; }
        public int TenantId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public long OrganizationUnitId { get; set; }
        public bool EnforceUniqueReference { get; set; }
        public string SpecificDataJsonSchema { get; set; }
        public string OutputDataJsonSchema { get; set; }
        public string AnalyticsDataJsonSchema { get; set; }
        public int SlaInMinutes { get; set; }
        public int RiskSlaInMinutes { get; set; }
        public Nullable<long> ReleaseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSchedules> ProcessSchedules { get; set; }
        public virtual Releases Releases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueItems> QueueItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueProcessingRecords> QueueProcessingRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueProcessingRecordsOld> QueueProcessingRecordsOld { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueProcessingRecordsStaging> QueueProcessingRecordsStaging { get; set; }
    }
}
