//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueueItems()
        {
            this.QueueItemComments = new HashSet<QueueItemComments>();
            this.QueueItemEvents = new HashSet<QueueItemEvents>();
        }
    
        public long Id { get; set; }
        public int Priority { get; set; }
        public long QueueDefinitionId { get; set; }
        public System.Guid Key { get; set; }
        public int Status { get; set; }
        public int ReviewStatus { get; set; }
        public Nullable<long> RobotId { get; set; }
        public Nullable<System.DateTime> StartProcessing { get; set; }
        public Nullable<System.DateTime> EndProcessing { get; set; }
        public int SecondsInPreviousAttempts { get; set; }
        public Nullable<long> AncestorId { get; set; }
        public int RetryNumber { get; set; }
        public string SpecificData { get; set; }
        public int TenantId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> DeferDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Progress { get; set; }
        public string Output { get; set; }
        public long OrganizationUnitId { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> ProcessingExceptionType { get; set; }
        public bool HasDueDate { get; set; }
        public string Reference { get; set; }
        public Nullable<long> ReviewerUserId { get; set; }
        public string ProcessingExceptionReason { get; set; }
        public string ProcessingExceptionDetails { get; set; }
        public string ProcessingExceptionAssociatedImageFilePath { get; set; }
        public Nullable<System.DateTime> ProcessingExceptionCreationTime { get; set; }
        public Nullable<long> CreatorJobId { get; set; }
        public Nullable<long> ExecutorJobId { get; set; }
        public string AnalyticsData { get; set; }
        public Nullable<System.DateTime> RiskSlaDate { get; set; }
        public Nullable<bool> HasRiskSlaDate { get; set; }
    
        public virtual QueueDefinitions QueueDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueItemComments> QueueItemComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueItemEvents> QueueItemEvents { get; set; }
        public virtual Robots Robots { get; set; }
        public virtual Users Users { get; set; }
    }
}
