//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robots
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Robots()
        {
            this.AssetValues = new HashSet<AssetValues>();
            this.ExecutionMedia = new HashSet<ExecutionMedia>();
            this.Jobs = new HashSet<Jobs>();
            this.QueueItems = new HashSet<QueueItems>();
            this.RobotLicenseLogs = new HashSet<RobotLicenseLogs>();
            this.RobotLicenses = new HashSet<RobotLicenses>();
            this.Sessions = new HashSet<Sessions>();
            this.ProcessSchedules = new HashSet<ProcessSchedules>();
            this.Environments = new HashSet<Environments>();
        }
    
        public long Id { get; set; }
        public string Key { get; set; }
        public string LicenseKey { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public int Type { get; set; }
        public string RobotDescription { get; set; }
        public int TenantId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> OrganizationUnitId { get; set; }
        public string ExecutionSettingsData { get; set; }
        public Nullable<long> MachineId { get; set; }
        public int HostingType { get; set; }
        public string Version { get; set; }
        public Nullable<long> UserId { get; set; }
        public int ProvisionType { get; set; }
        public bool IsExternalLicensed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetValues> AssetValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionMedia> ExecutionMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs> Jobs { get; set; }
        public virtual Machines Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueItems> QueueItems { get; set; }
        public virtual RobotCredentials RobotCredentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RobotLicenseLogs> RobotLicenseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RobotLicenses> RobotLicenses { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessSchedules> ProcessSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Environments> Environments { get; set; }
    }
}
