//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotLicenseStats
    {
        public long Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int RobotType { get; set; }
        public long MaxRobotsCount { get; set; }
        public int TenantId { get; set; }
    }
}
