//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotLicenses
    {
        public Nullable<long> RobotId { get; set; }
        public int RobotType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int TenantId { get; set; }
        public long Id { get; set; }
        public string Key { get; set; }
        public int Scope { get; set; }
        public int Slots { get; set; }
        public string LicenseKey { get; set; }
        public bool Enabled { get; set; }
        public string Properties { get; set; }
    
        public virtual Robots Robots { get; set; }
    }
}
