//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public long Id { get; set; }
        public int TenantId { get; set; }
        public int State { get; set; }
        public Nullable<long> RobotId { get; set; }
        public Nullable<long> JobId { get; set; }
        public System.DateTime ReportingTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public long OrganizationUnitId { get; set; }
        public bool IsUnresponsive { get; set; }
        public string HostMachineName { get; set; }
        public Nullable<long> MachineId { get; set; }
        public Nullable<int> LicenseErrorCode { get; set; }
    
        public virtual Jobs Jobs { get; set; }
        public virtual Machines Machines { get; set; }
        public virtual Robots Robots { get; set; }
    }
}
