//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessErrorV2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRobotAssociatedProcesses
    {
        public long RobotId { get; set; }
        public string RobotKey { get; set; }
        public string RobotName { get; set; }
        public Nullable<long> ReleaseId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Key { get; set; }
        public string ProcessKey { get; set; }
    }
}
